# Run test suite.
image: golang:1.12.7-buster

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/pkg

stages:
  - build

build:
  stage: build
  script:
      go test -v ./...
  tags: [docker]

